- name: Add MongoDB repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6
    state: present

- name: Add MongoDB repo
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/{{ ubuntu_mongodb.version }} multiverse"
    state: present

- name: Install MongoDB package
  apt:
    name: mongodb-org
    state: present
