- name: Install packages required by popular gems
  apt: name={{item}} state=latest
  with_items:
    - libxml2-dev
    - libffi-dev
    - libyaml-dev
    - libssl-dev
    - libsqlite3-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline6-dev
    - libyaml-dev
    - sqlite3
    - zlib1g-dev
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev
